---
title: "Paul Vernus's CV"
author:
  firstname: Paul
  lastname: Vernus
  address: "12 avenue d'Italie, 63000 Clermont-Ferrand, France"
  position: "Phd candidate, Economist"
  contacts:
    - icon: fa envelope
      text: paul.vernus@ferdi.fr
      url: "mailto:paul.vernus@ferdi.fr"
    # - icon: assets/icon/bi-house-fill.svg
    #   text: website.com
      # url: https://website.com
    # - icon: fa brands orcid
    #   text: 0000-0000-0000-0000
    #   url: https://orcid.org/0000-0000-0000-0000
    - icon: fa brands github
      text: GitHub
      url: https://github.com/pvernus
    - icon: fa brands linkedin
      text: LinkedIn
      url: https://www.linkedin.com/in/paul-vernus-09538214b/
    # - icon: fa brands x-twitter
    #   text: twitter
    #   url: https://twitter.com/example
format: awesomecv-typst
brand:
  typography: 
    fonts:
      - family: Roboto
        source: google
        weight: [100, 400, 700]
      - family: Source Sans 3
        source: google
        weight: [100, 400, 700]
        style: [normal, italic]
    base: Source Sans 3
  color:
    primary: "#832b6d"
    link: "#5c1e4c"
  defaults: 
    awesomecv-typst:
      font-header: Roboto
---

```{r}
library(typstcv)
```

## Work Experience

```{r}
#| output: asis
read.csv(
  "data/work.csv",
  colClasses = c("character", "character", "Date", "Date", "character")
) |> 
  format_date(end = "end", sort_by = "start") |> 
  resume_entry(title = "degree", description = "institution")

```

## Education

```{r}
#| output: asis
read.csv(
  "data/education.csv",
  sep = ";",
  colClasses = c("character", "character", "Date", "Date", "character", "character")
) |> 
  format_date(end = "end", sort_by = "start") |> 
  resume_entry(title = "degree", location = "location", description = "description")

```

## Languages & Certifications

```{r}
#| output: asis
read.csv(
  "data/skill.csv",
  sep = ";",
  colClasses = c("character", "character", "character", "Date")
) |> 
  resume_entry(title = "skill", description = "institution")

```

